<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>MeshDrive.Agent</RootNamespace>
    <AssemblyName>MeshDrive.Agent</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MeshDrive.Core\MeshDrive.Core.csproj" />
    <ProjectReference Include="..\MeshDrive.Protocol\MeshDrive.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
  </ItemGroup>
</Project>
